user "root"; 
private_key "/home/jmerelo/.ssh/jj-iv.pem";
public_key "/home/jmerelo/.ssh/jj-iv.pem.pub";
key_auth;

group fiware => "130.206.127.211";

desc "Install emacs";
task "emacs", group => "fiware", sub {
     install 'emacs';
};


